# Generated by Django 3.2 on 2022-02-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.PositiveSmallIntegerField(null=True)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_method', models.CharField(max_length=15)),
                ('payment_is_cleared', models.BooleanField()),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PayeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_address_line_1', models.CharField(max_length=50)),
                ('payee_address_line_2', models.CharField(max_length=50)),
                ('payee_address_city', models.CharField(max_length=20)),
                ('payee_address_county', models.CharField(max_length=25)),
                ('payee_address_eircode', models.CharField(max_length=7)),
                ('payee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.payee')),
            ],
            options={
                'ordering': ['-payee_name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.SmallIntegerField(blank=True, null=True)),
                ('invoice_date', models.DateField()),
                ('invoice_sent_date', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('payee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.payee')),
                ('payment_number', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='billing_app.paymentdetails')),
            ],
            options={
                'ordering': ['-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField()),
                ('appointment_type', models.CharField(choices=[('AP', 'Appointment'), ('NS', 'No-Show'), ('LC', 'Late Cancellation')], default='AP', max_length=2)),
                ('appointment_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('invoice_number', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='billing_app.invoice')),
            ],
            options={
                'ordering': ['-appointment_datetime'],
            },
        ),
    ]
