# Generated by Django 3.2 on 2022-02-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[(1, 'Appointment'), (2, 'Late Cancellation'), (3, 'No-Show')], default='Appointment', max_length=30),
        ),
    ]
