# Generated by Django 3.2 on 2022-02-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Appointment'), (2, 'Late Cancellation'), (3, 'No-Show')], default=1),
        ),
    ]
